//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GersonCastillo_Pro.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GersonCastillo_Pro.Client.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English for Academic Purposes (LEAP).
        /// </summary>
        public static string AcademicDegree1 {
            get {
                return ResourceManager.GetString("AcademicDegree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business English Certificate.
        /// </summary>
        public static string AcademicDegree2 {
            get {
                return ResourceManager.GetString("AcademicDegree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attorney.
        /// </summary>
        public static string AcademicDegree3 {
            get {
                return ResourceManager.GetString("AcademicDegree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bachelor&apos;s Degree in Accounting.
        /// </summary>
        public static string AcademicDegree4 {
            get {
                return ResourceManager.GetString("AcademicDegree4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Academic Degrees.
        /// </summary>
        public static string AcademicDegrees {
            get {
                return ResourceManager.GetString("AcademicDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @action.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artificial Intelligence and Data Science.
        /// </summary>
        public static string AIDataScience {
            get {
                return ResourceManager.GetString("AIDataScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web App loading....
        /// </summary>
        public static string AppLoading {
            get {
                return ResourceManager.GetString("AppLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blazor WebAssembly.
        /// </summary>
        public static string BlazorWebAssembly {
            get {
                return ResourceManager.GetString("BlazorWebAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expertise and Advanced Knowledge in Financial Consolidation, Accounting, and Auditing (IFRS, PGC, and NOFCAC).
        /// </summary>
        public static string BusinessSkill1 {
            get {
                return ResourceManager.GetString("BusinessSkill1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced knowledge in financial, investment, and business management..
        /// </summary>
        public static string BusinessSkill2 {
            get {
                return ResourceManager.GetString("BusinessSkill2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excellent ability for comprehensive risk assessment and development of effective strategies..
        /// </summary>
        public static string BusinessSkill3 {
            get {
                return ResourceManager.GetString("BusinessSkill3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal controls process automation..
        /// </summary>
        public static string BusinessSkill4 {
            get {
                return ResourceManager.GetString("BusinessSkill4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial Reports Automation, ETL &amp; ELT Processes, with Advanced Proficiency in Reporting and Data Modeling Tools such as Power BI and Excel.
        /// </summary>
        public static string BusinessSkill5 {
            get {
                return ResourceManager.GetString("BusinessSkill5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accounting entries automation..
        /// </summary>
        public static string BusinessSkill6 {
            get {
                return ResourceManager.GetString("BusinessSkill6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank reconciliation automation..
        /// </summary>
        public static string BusinessSkill7 {
            get {
                return ResourceManager.GetString("BusinessSkill7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payments automation..
        /// </summary>
        public static string BusinessSkill8 {
            get {
                return ResourceManager.GetString("BusinessSkill8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data entry Automation..
        /// </summary>
        public static string BusinessSkill9 {
            get {
                return ResourceManager.GetString("BusinessSkill9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business Skills.
        /// </summary>
        public static string BusinessSkills {
            get {
                return ResourceManager.GetString("BusinessSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key business competencies and leadership qualities.
        /// </summary>
        public static string BusinessSkillsIntro {
            get {
                return ResourceManager.GetString("BusinessSkillsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reach out to me through my social media or mail..
        /// </summary>
        public static string ContactSubtitle {
            get {
                return ResourceManager.GetString("ContactSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting in touch with me.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Courses &amp; Certifications.
        /// </summary>
        public static string CoursesCertifications {
            get {
                return ResourceManager.GetString("CoursesCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madrid, Comunidad de Madrid, Spain · On-Site.
        /// </summary>
        public static string CurrentJob1Location {
            get {
                return ResourceManager.GetString("CurrentJob1Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Konsolidator Iberia · Full-Time 2024 - Present.
        /// </summary>
        public static string CurrentJob1Period {
            get {
                return ResourceManager.GetString("CurrentJob1Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expert in Financial Consolidation: Proficient in managing and optimizing financial consolidation processes..
        /// </summary>
        public static string CurrentJob1Responsibility1 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Specialist: In-depth knowledge of product functionalities and applications..
        /// </summary>
        public static string CurrentJob1Responsibility2 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial Statement Analysis Specialist: Experienced in analyzing and interpreting financial statements for accurate reporting..
        /// </summary>
        public static string CurrentJob1Responsibility3 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accounting and Auditing Specialist: Expert in PGC, NOFCAC, IFRS, and IAS standards, ensuring compliance and accuracy..
        /// </summary>
        public static string CurrentJob1Responsibility4 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial Reporting and Business Intelligence Specialist: Advanced skills in Power BI, Advanced Excel, SQL, and M Language for robust financial reporting and analysis..
        /// </summary>
        public static string CurrentJob1Responsibility5 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automation Solutions Developer: Proficient in creating automation solutions using REST API, .Net Core, and SQL Server to streamline processes and enhance efficiency..
        /// </summary>
        public static string CurrentJob1Responsibility6 {
            get {
                return ResourceManager.GetString("CurrentJob1Responsibility6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Success Manager.
        /// </summary>
        public static string CurrentJob1Title1 {
            get {
                return ResourceManager.GetString("CurrentJob1Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Consolidation specialist).
        /// </summary>
        public static string CurrentJob1Title2 {
            get {
                return ResourceManager.GetString("CurrentJob1Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redemerca LLC 2019-Present.
        /// </summary>
        public static string CurrentJob2Period {
            get {
                return ResourceManager.GetString("CurrentJob2Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Investment portfolio&apos;s management. (Stock, Options &amp; Futures)..
        /// </summary>
        public static string CurrentJob2Responsibility1 {
            get {
                return ResourceManager.GetString("CurrentJob2Responsibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Market and company analysis..
        /// </summary>
        public static string CurrentJob2Responsibility2 {
            get {
                return ResourceManager.GetString("CurrentJob2Responsibility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software development focused on market analysis..
        /// </summary>
        public static string CurrentJob2Responsibility3 {
            get {
                return ResourceManager.GetString("CurrentJob2Responsibility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business owner.
        /// </summary>
        public static string CurrentJob2Title1 {
            get {
                return ResourceManager.GetString("CurrentJob2Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Development Tools.
        /// </summary>
        public static string DevelopmentTools {
            get {
                return ResourceManager.GetString("DevelopmentTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download PowerPoint presentation.
        /// </summary>
        public static string DownloadPowerPoint {
            get {
                return ResourceManager.GetString("DownloadPowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I was involved in the five steps of software development of the App&apos;s financial, accountant, and administrative components. I also taught programming to our team&apos;s newest members..
        /// </summary>
        public static string EnterpriseProject1Action {
            get {
                return ResourceManager.GetString("EnterpriseProject1Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The second version of the groceries eCommerce web app was developed to exploit the potential of the latest technologies from Microsoft ASP.NET Core..
        /// </summary>
        public static string EnterpriseProject1Description {
            get {
                return ResourceManager.GetString("EnterpriseProject1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Commerce 2.0 Year: 2021.
        /// </summary>
        public static string EnterpriseProject1Title {
            get {
                return ResourceManager.GetString("EnterpriseProject1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My participation comprehended the App&apos;s financial and accounting development..
        /// </summary>
        public static string EnterpriseProject2Action {
            get {
                return ResourceManager.GetString("EnterpriseProject2Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groceries eCommerce web app fully integrated with the ERP SAP Business One to attend to around 40,000 retail customers..
        /// </summary>
        public static string EnterpriseProject2Description {
            get {
                return ResourceManager.GetString("EnterpriseProject2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Commerce 1.0 Year: 2019.
        /// </summary>
        public static string EnterpriseProject2Title {
            get {
                return ResourceManager.GetString("EnterpriseProject2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I participated in developing the accounting, financial and administrative modules..
        /// </summary>
        public static string EnterpriseProject3Action {
            get {
                return ResourceManager.GetString("EnterpriseProject3Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal software of gestion of logistics and administration process, developed under .NET technology fully integrated with the ERP SAP Business One..
        /// </summary>
        public static string EnterpriseProject3Description {
            get {
                return ResourceManager.GetString("EnterpriseProject3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GC Internal Management Software: 2017.
        /// </summary>
        public static string EnterpriseProject3Title {
            get {
                return ResourceManager.GetString("EnterpriseProject3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I developed the whole project..
        /// </summary>
        public static string EnterpriseProject4Action {
            get {
                return ResourceManager.GetString("EnterpriseProject4Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program for automatic management of banking and accounting..
        /// </summary>
        public static string EnterpriseProject4Description {
            get {
                return ResourceManager.GetString("EnterpriseProject4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banking and Accounting automatized: 2016.
        /// </summary>
        public static string EnterpriseProject4Title {
            get {
                return ResourceManager.GetString("EnterpriseProject4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language selection flag.
        /// </summary>
        public static string FlagImageAlt {
            get {
                return ResourceManager.GetString("FlagImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This website has been developed by Gerson Castillo © {0} Copyright; using.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from ASP.NET Core..
        /// </summary>
        public static string FooterTechStack {
            get {
                return ResourceManager.GetString("FooterTechStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This website has been developed by Gerson Castillo ©{0} Copyright; using.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frameworks.
        /// </summary>
        public static string Frameworks {
            get {
                return ResourceManager.GetString("Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from ASP.NET Core..
        /// </summary>
        public static string FromAspNetCore {
            get {
                return ResourceManager.GetString("FromAspNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @import.
        /// </summary>
        public static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Senior Technology Leader with more than 15 years of proven experience in directing multidisciplinary teams (50+ members), financial strategy, and end-to-end software development. My career is distinguished by the ability to transform complex business challenges into robust, scalable technological solutions with a direct impact on financial performance..
        /// </summary>
        public static string IntroDescription {
            get {
                return ResourceManager.GetString("IntroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Transforming complex business challenges into scalable technology solutions.&quot;.
        /// </summary>
        public static string IntroQuote {
            get {
                return ResourceManager.GetString("IntroQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estratega de IA | AI/GenAI Engineer &amp; Arquitecto de Soluciones.
        /// </summary>
        public static string IntroSubtitle {
            get {
                return ResourceManager.GetString("IntroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líder de Transformación Digital Financiera  .
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language Selector.
        /// </summary>
        public static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ability to set a clear vision, align objectives, and turn strategy into tangible results..
        /// </summary>
        public static string Leadership_Item1_Text {
            get {
                return ResourceManager.GetString("Leadership_Item1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strategic leadership.
        /// </summary>
        public static string Leadership_Item1_Title {
            get {
                return ResourceManager.GetString("Leadership_Item1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I take end-to-end ownership of projects with initiative, commitment, and execution focus..
        /// </summary>
        public static string Leadership_Item10_Text {
            get {
                return ResourceManager.GetString("Leadership_Item10_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrepreneurial mindset.
        /// </summary>
        public static string Leadership_Item10_Title {
            get {
                return ResourceManager.GetString("Leadership_Item10_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experience leading diverse roles, fostering collaboration and high performance..
        /// </summary>
        public static string Leadership_Item2_Text {
            get {
                return ResourceManager.GetString("Leadership_Item2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multidisciplinary team management.
        /// </summary>
        public static string Leadership_Item2_Title {
            get {
                return ResourceManager.GetString("Leadership_Item2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I connect finance, technology, and data to deliver complete and sustainable solutions..
        /// </summary>
        public static string Leadership_Item3_Text {
            get {
                return ResourceManager.GetString("Leadership_Item3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tech–functional mindset.
        /// </summary>
        public static string Leadership_Item3_Title {
            get {
                return ResourceManager.GetString("Leadership_Item3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I drive operational efficiency and continuous improvement, measuring impact rigorously..
        /// </summary>
        public static string Leadership_Item4_Text {
            get {
                return ResourceManager.GetString("Leadership_Item4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results orientation.
        /// </summary>
        public static string Leadership_Item4_Title {
            get {
                return ResourceManager.GetString("Leadership_Item4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I promote digital transformation and the adoption of new technologies across processes..
        /// </summary>
        public static string Leadership_Item5_Text {
            get {
                return ResourceManager.GetString("Leadership_Item5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Innovation driver.
        /// </summary>
        public static string Leadership_Item5_Title {
            get {
                return ResourceManager.GetString("Leadership_Item5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I inspire, mentor, and upskill teams to grow their autonomy and impact..
        /// </summary>
        public static string Leadership_Item6_Text {
            get {
                return ResourceManager.GetString("Leadership_Item6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent development.
        /// </summary>
        public static string Leadership_Item6_Title {
            get {
                return ResourceManager.GetString("Leadership_Item6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I rely on trustworthy analytics and information for planning and management..
        /// </summary>
        public static string Leadership_Item7_Text {
            get {
                return ResourceManager.GetString("Leadership_Item7_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data-driven decisions.
        /// </summary>
        public static string Leadership_Item7_Title {
            get {
                return ResourceManager.GetString("Leadership_Item7_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I bridge leadership, technical teams, and clients to ensure alignment and clarity..
        /// </summary>
        public static string Leadership_Item8_Text {
            get {
                return ResourceManager.GetString("Leadership_Item8_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effective communication.
        /// </summary>
        public static string Leadership_Item8_Title {
            get {
                return ResourceManager.GetString("Leadership_Item8_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I act responsibly, ensuring transparency, internal control, and regulatory compliance..
        /// </summary>
        public static string Leadership_Item9_Text {
            get {
                return ResourceManager.GetString("Leadership_Item9_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrity and compliance.
        /// </summary>
        public static string Leadership_Item9_Title {
            get {
                return ResourceManager.GetString("Leadership_Item9_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leadership Qualities.
        /// </summary>
        public static string Leadership_Title {
            get {
                return ResourceManager.GetString("Leadership_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Navigation.
        /// </summary>
        public static string MainNavigation {
            get {
                return ResourceManager.GetString("MainNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .NET Frameworks &amp; Libraries.
        /// </summary>
        public static string NetFrameworksLibraries {
            get {
                return ResourceManager.GetString("NetFrameworksLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Newest Courses &amp; Certifications.
        /// </summary>
        public static string NewestCoursesCertifications {
            get {
                return ResourceManager.GetString("NewestCoursesCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other Frameworks &amp; Libraries.
        /// </summary>
        public static string OtherFrameworksLibraries {
            get {
                return ResourceManager.GetString("OtherFrameworksLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professional portfolio of Gerson Castillo, specialist in financial consolidation, automation, and software development..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerson Castillo - Financial Consolidation &amp; Automation Specialist.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marluis Investments 2006-2022.
        /// </summary>
        public static string PastJob1Period {
            get {
                return ResourceManager.GetString("PastJob1Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Management of the accounting, auditing, financial, administrative, and human resources areas..
        /// </summary>
        public static string PastJob1Responsibility1 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modeling and preparation of financial statements under IFRS standards..
        /// </summary>
        public static string PastJob1Responsibility2 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Development of investment plans and strategies, budgets, and tax planning..
        /// </summary>
        public static string PastJob1Responsibility3 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervision of administrative and accounting processes, internal auditing, internal control, and personnel management..
        /// </summary>
        public static string PastJob1Responsibility4 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software development and management of financial operations automation processes..
        /// </summary>
        public static string PastJob1Responsibility5 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Development of ETL and ELT processes, ASP.NET Core, SQL Server, Power BI, Power Query, DAX..
        /// </summary>
        public static string PastJob1Responsibility6 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial and accounting integration of internal software developments with the ERP system SAP Business One..
        /// </summary>
        public static string PastJob1Responsibility7 {
            get {
                return ResourceManager.GetString("PastJob1Responsibility7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director of Finance And Administration.
        /// </summary>
        public static string PastJob1Title1 {
            get {
                return ResourceManager.GetString("PastJob1Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I developed the whole exercise..
        /// </summary>
        public static string PersonalProject1Action {
            get {
                return ResourceManager.GetString("PersonalProject1Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I have prepared a comprehensive financial consolidation exercise utilizing Power BI and DAX functions. This exercise aims to demonstrate the main principles of financial consolidation under the IFRS standards, specifically IAS 21. The final financial reports have been embedded into a web page using Power BI Embedded for seamless access and interaction..
        /// </summary>
        public static string PersonalProject1Description {
            get {
                return ResourceManager.GetString("PersonalProject1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presentation of Financial Consolidation Exercise: 2024.
        /// </summary>
        public static string PersonalProject1Title {
            get {
                return ResourceManager.GetString("PersonalProject1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I developed the whole project..
        /// </summary>
        public static string PersonalProject2Action {
            get {
                return ResourceManager.GetString("PersonalProject2Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professional web page..
        /// </summary>
        public static string PersonalProject2Description {
            get {
                return ResourceManager.GetString("PersonalProject2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal web page: 2023.
        /// </summary>
        public static string PersonalProject2Title {
            get {
                return ResourceManager.GetString("PersonalProject2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I developed the whole project..
        /// </summary>
        public static string PersonalProject3Action {
            get {
                return ResourceManager.GetString("PersonalProject3Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program to analyze the currency derivatives market..
        /// </summary>
        public static string PersonalProject3Description {
            get {
                return ResourceManager.GetString("PersonalProject3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7Gplus: 2017.
        /// </summary>
        public static string PersonalProject3Title {
            get {
                return ResourceManager.GetString("PersonalProject3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presentation.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Repository.
        /// </summary>
        public static string PrivateRepository {
            get {
                return ResourceManager.GetString("PrivateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerson Castillo.
        /// </summary>
        public static string ProfessionalTitle {
            get {
                return ResourceManager.GetString("ProfessionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerson Castillo Profile Photo.
        /// </summary>
        public static string ProfileImageAlt {
            get {
                return ResourceManager.GetString("ProfileImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public Repository.
        /// </summary>
        public static string PublicRepository {
            get {
                return ResourceManager.GetString("PublicRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositories.
        /// </summary>
        public static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skills &amp; Technologies.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip to main content.
        /// </summary>
        public static string SkipToContent {
            get {
                return ResourceManager.GetString("SkipToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software Development.
        /// </summary>
        public static string SoftwareDevelopment {
            get {
                return ResourceManager.GetString("SoftwareDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programming Languages.
        /// </summary>
        public static string SoftwareLanguages {
            get {
                return ResourceManager.GetString("SoftwareLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some projects.
        /// </summary>
        public static string SomeProjects {
            get {
                return ResourceManager.GetString("SomeProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Technical Skills.
        /// </summary>
        public static string TechnicalSkills {
            get {
                return ResourceManager.GetString("TechnicalSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @using.
        /// </summary>
        public static string UsingLabel {
            get {
                return ResourceManager.GetString("UsingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web App loading....
        /// </summary>
        public static string WebAppLoading {
            get {
                return ResourceManager.GetString("WebAppLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Projects.
        /// </summary>
        public static string WorkProjects {
            get {
                return ResourceManager.GetString("WorkProjects", resourceCulture);
            }
        }
    }
}
